name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Run cibuild
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
        run: bin/cibuild
