name: update
on:
  schedule:
    - cron: '* 15 * * *'
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Run bin/update
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          git config --local user.name "GitHub"
          git config --local user.email "noreply@github.com"
          bin/update
